export default {
  BLOCK_UI: 'BLOCK_UI',
  UNBLOCK_UI: 'UNBLOCK_UI',
  TOGGLE_SEARCH: 'TOGGLE_SEARCH',
  NOTIFICATION: 'NOTIFICATION',
  REQUEST_ERROR: 'REQUEST_ERROR',
  SEARCH_LINES: 'SEARCH_LINES',
  SELECT_LINE: 'SELECT_LINE',
  TOGGLE_LINE_DIRECTION: 'TOGGLE_LINE_DIRECTION',
  GET_LINE_ROUTE: 'GET_LINE_ROUTE',
  GET_LINE_POSITIONS: 'GET_LINE_POSITIONS',
  SAVE_FAVORITE_LINE: 'SAVE_FAVORITE_LINE',
  REMOVE_FAVORITE_LINE: 'REMOVE_FAVORITE_LINE',
};
